name: skadi_plus
description: Utilities widgets and method on top of other Flutter's package.
version: 3.3.0

homepage: https://www.lynical.com
repository: https://github.com/lynical-software/skadi_plus
issue_tracker: https://github.com/lynical-software/skadi_plus/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.5.0+1
  url_launcher: ^6.3.0
  future_manager: ^1.11.0
  get_it: ^7.6.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  skadi: ^4.6.0
  oktoast: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
