name: skadi_plus
description: Utilities widgets and method on top of other Flutter's package.
version: 0.0.1

homepage: https://www.lynical.com
repository: https://github.com/lynical-software/skadi_plus
issue_tracker: https://github.com/lynical-software/skadi_plus/issues

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.5.1
  dio: ^4.0.6
  url_launcher: ^6.1.8
  future_manager: ^1.3.0
  get_it: ^7.2.0
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  skadi: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
